# The name of the Dataset (from the FF hub) to train on (could be your own private,
# dataset). It can also be a path pointing to a local copy of a dataset in your
# filesystem, or to a folder containing files that HF datasets can understand.
name: lambdalabs/pokemon-blip-captions
# The config of the Dataset, leave as None if there's only one config
config_name:
# A folder containing the training data. Folder contents must follow the structure
# described in https://huggingface.co/docs/datasets/image_dataset#imagefolder. In
# particular, a `metadata.jsonl` file" must exist to provide the captions for the
# images. Ignored if `dataset_name` is specified."
train_data_dir:

# The column of the dataset containing an image.
image_column: image
# The column of the dataset containing a caption or a list of captions.
caption_column: text