# TODO:
# instantiation from the main file.
# Initialize the optimizer
# if args.use_8bit_adam:
#     try:
#         import bitsandbytes as bnb
#     except ImportError:
#         raise ImportError(
#             "Please install bitsandbytes to use 8-bit Adam. You can do so by running `pip install bitsandbytes`"
#         )

#     optimizer_cls = bnb.optim.AdamW8bit